feat(workflow): add deployment step to server in GitHub Actions
- Introduced a new job in the GitHub Actions workflow to deploy the application to a server.
- Utilized curl to send a POST request for deployment, including repository and commit information.
- Added error handling to exit the job if the deployment request fails.

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -36,3 +36,28 @@ jobs:
         tags: ghcr.io/mnofresno/random-games:0.0.1
         labels: |
           org.opencontainers.image.source=${{ github.repository }}
+
+    - name: Deploy to Server
+      env:
+        AUTODEPLOY_URL: ${{ vars.AUTODEPLOY_URL }}
+        KEY_FILE_FOR_DEPLOY: ${{ secrets.KEY_FILE_FOR_DEPLOY }}
+      run: |
+          response=$(curl -X POST \
+              -H "Content-Type: application/json" \
+              -d '{
+                  "repo": "random-games",
+                  "key": "'"${KEY_FILE_FOR_DEPLOY}"'",
+                  "run_in_background": true,
+                  "commit": {
+                      "sha": "'"${{ github.sha }}"'",
+                      "author": "'"${{ github.actor }}"'"
+                  }
+                  }' \
+              -s -o response_body.txt -w "%{http_code}" \
+              --fail \
+              "https://${AUTODEPLOY_URL}?repo=random-games&key=${KEY_FILE_FOR_DEPLOY}&create_repo_if_not_exists=true"
+          cat response_body.tx
+          if [ "$response" -ge 400 ]; then
+              echo "Request failed with status code $response"
+              exit 1
+          fi
